/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace XRoad.Sdk.Model;

/// <summary>
/// DistinguishedName
/// </summary>
[DataContract(Name = "DistinguishedName")]
public class DistinguishedName : IEquatable<DistinguishedName>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="DistinguishedName" /> class.
    /// </summary>
    /// <param name="name">distinguished name.</param>
    public DistinguishedName(string name = default)
    {
        Name = name;
    }

    /// <summary>
    /// distinguished name
    /// </summary>
    /// <value>distinguished name</value>
    [DataMember(Name = "name", EmitDefaultValue = false)]
    public string Name { get; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class DistinguishedName {\n");
        sb.Append("  Name: ").Append(Name).Append('\n');
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return Equals(input as DistinguishedName);
    }

    /// <summary>
    /// Returns true if DistinguishedName instances are equal
    /// </summary>
    /// <param name="input">Instance of DistinguishedName to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(DistinguishedName input)
    {
        if (input == null) return false;
        return
            Name == input.Name ||
            (Name != null &&
             Name.Equals(input.Name));
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            if (Name != null) hashCode = hashCode * 59 + Name.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        // Name (string) maxLength
        if (Name is {Length: > 255})
            yield return new ValidationResult("Invalid value for Name, length must be less than 255.", new[] {"Name"});

        // Name (string) minLength
        if (Name is {Length: < 1})
            yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new[] {"Name"});
    }
}