/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace XRoad.Sdk.Model;

/// <summary>
/// language
/// </summary>
[DataContract(Name = "Language")]
public class Language : IEquatable<Language>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="Language" /> class.
    /// </summary>
    [JsonConstructor]
    public Language()
    {
    }

    /// <summary>
    /// language code
    /// </summary>
    /// <value>language code</value>
    [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = false)]
    public string Id { get; }

    /// <summary>
    /// Returns false as Id should not be serialized given that it's read-only.
    /// </summary>
    /// <returns>false (boolean)</returns>
    public bool ShouldSerializeId()
    {
        return false;
    }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class Language {\n");
        sb.Append("  Id: ").Append(Id).Append('\n');
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return Equals(input as Language);
    }

    /// <summary>
    /// Returns true if Language instances are equal
    /// </summary>
    /// <param name="input">Instance of Language to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(Language input)
    {
        if (input == null) return false;
        return
            Id == input.Id ||
            (Id != null &&
             Id.Equals(input.Id));
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            if (Id != null) hashCode = hashCode * 59 + Id.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        // Id (string) maxLength
        if (Id != null && Id.Length > 2)
            yield return new ValidationResult("Invalid value for Id, length must be less than 2.", new[] {"Id"});

        // Id (string) minLength
        if (Id != null && Id.Length < 2)
            yield return new ValidationResult("Invalid value for Id, length must be greater than 2.", new[] {"Id"});
    }
}