/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace XRoad.Sdk.Model;

/// <summary>
/// model for adding a new LocalGroup
/// </summary>
[DataContract(Name = "LocalGroupAdd")]
public class LocalGroupAdd : IEquatable<LocalGroupAdd>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="LocalGroupAdd" /> class.
    /// </summary>
    [JsonConstructor]
    protected LocalGroupAdd()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="LocalGroupAdd" /> class.
    /// </summary>
    /// <param name="code">group code (required).</param>
    /// <param name="description">group description (required).</param>
    public LocalGroupAdd(string code = default, string description = default)
    {
        // to ensure "code" is required (not null)
        Code = code ?? throw new ArgumentNullException(nameof(code),"code is a required property for LocalGroupAdd and cannot be null");
        // to ensure "description" is required (not null)
        Description = description ?? throw new ArgumentNullException(nameof(description),"description is a required property for LocalGroupAdd and cannot be null");
    }

    /// <summary>
    /// group code
    /// </summary>
    /// <value>group code</value>
    [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = false)]
    public string Code { get; }

    /// <summary>
    /// group description
    /// </summary>
    /// <value>group description</value>
    [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = false)]
    public string Description { get; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class LocalGroupAdd {\n");
        sb.Append("  Code: ").Append(Code).Append('\n');
        sb.Append("  Description: ").Append(Description).Append('\n');
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return Equals(input as LocalGroupAdd);
    }

    /// <summary>
    /// Returns true if LocalGroupAdd instances are equal
    /// </summary>
    /// <param name="input">Instance of LocalGroupAdd to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(LocalGroupAdd input)
    {
        if (input == null) return false;
        return
            (
                Code == input.Code ||
                (Code != null &&
                 Code.Equals(input.Code))
            ) &&
            (
                Description == input.Description ||
                (Description != null &&
                 Description.Equals(input.Description))
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            if (Code != null) hashCode = hashCode * 59 + Code.GetHashCode();
            if (Description != null) hashCode = hashCode * 59 + Description.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        // Code (string) maxLength
        if (Code is {Length: > 255})
            yield return new ValidationResult("Invalid value for Code, length must be less than 255.", new[] {"Code"});

        // Code (string) minLength
        if (Code is {Length: < 1})
            yield return new ValidationResult("Invalid value for Code, length must be greater than 1.", new[] {"Code"});

        // Description (string) maxLength
        if (Description is {Length: > 255})
            yield return new ValidationResult("Invalid value for Description, length must be less than 255.",
                new[] {"Description"});

        // Description (string) minLength
        if (Description is {Length: < 1})
            yield return new ValidationResult("Invalid value for Description, length must be greater than 1.",
                new[] {"Description"});
    }
}