/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace XRoad.Sdk.Model;

/// <summary>
/// OrphanInformation
/// </summary>
[DataContract(Name = "OrphanInformation")]
public class OrphanInformation : IEquatable<OrphanInformation>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="OrphanInformation" /> class.
    /// </summary>
    /// <param name="orphansExist">orphansExist (default to false).</param>
    public OrphanInformation(bool orphansExist = false)
    {
        OrphansExist = orphansExist;
    }

    /// <summary>
    /// Gets or Sets OrphansExist
    /// </summary>
    [DataMember(Name = "orphans_exist", EmitDefaultValue = true)]
    public bool OrphansExist { get; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class OrphanInformation {\n");
        sb.Append("  OrphansExist: ").Append(OrphansExist).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return Equals(input as OrphanInformation);
    }

    /// <summary>
    /// Returns true if OrphanInformation instances are equal
    /// </summary>
    /// <param name="input">Instance of OrphanInformation to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(OrphanInformation input)
    {
        if (input == null) return false;
        return
            OrphansExist == input.OrphansExist ||
            OrphansExist.Equals(input.OrphansExist);
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            hashCode = hashCode * 59 + OrphansExist.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        yield break;
    }
}