/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace XRoad.Sdk.Model;

/// <summary>
/// ServiceDescriptionDisabledNotice
/// </summary>
[DataContract(Name = "ServiceDescriptionDisabledNotice")]
public class ServiceDescriptionDisabledNotice : IEquatable<ServiceDescriptionDisabledNotice>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ServiceDescriptionDisabledNotice" /> class.
    /// </summary>
    /// <param name="disabledNotice">disabled service notice.</param>
    public ServiceDescriptionDisabledNotice(string disabledNotice = default)
    {
        DisabledNotice = disabledNotice;
    }

    /// <summary>
    /// disabled service notice
    /// </summary>
    /// <value>disabled service notice</value>
    [DataMember(Name = "disabled_notice", EmitDefaultValue = false)]
    public string DisabledNotice { get; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class ServiceDescriptionDisabledNotice {\n");
        sb.Append("  DisabledNotice: ").Append(DisabledNotice).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return Equals(input as ServiceDescriptionDisabledNotice);
    }

    /// <summary>
    /// Returns true if ServiceDescriptionDisabledNotice instances are equal
    /// </summary>
    /// <param name="input">Instance of ServiceDescriptionDisabledNotice to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(ServiceDescriptionDisabledNotice input)
    {
        if (input == null) return false;
        return
            DisabledNotice == input.DisabledNotice ||
            (DisabledNotice != null &&
             DisabledNotice.Equals(input.DisabledNotice));
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            if (DisabledNotice != null) hashCode = hashCode * 59 + DisabledNotice.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        if (DisabledNotice is {Length: > 255})
            yield return new ValidationResult("Invalid value for DisabledNotice, length must be less than 255.",
                new[] {"DisabledNotice"});
    }
}