/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace XRoad.Sdk.Model;

/// <summary>
/// request object for updating a service description url or service code
/// </summary>
[DataContract(Name = "ServiceDescriptionUpdate")]
public class ServiceDescriptionUpdate : IEquatable<ServiceDescriptionUpdate>, IValidatableObject
{
    /// <summary>
    /// Gets or Sets Type
    /// </summary>
    [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = false)]
    public ServiceType Type { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="ServiceDescriptionUpdate" /> class.
    /// </summary>
    [JsonConstructor]
    protected ServiceDescriptionUpdate()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="ServiceDescriptionUpdate" /> class.
    /// </summary>
    /// <param name="url">path for the service description file (required).</param>
    /// <param name="restServiceCode">service code for REST service.</param>
    /// <param name="newRestServiceCode">new service code for REST service.</param>
    /// <param name="ignoreWarnings">if true, any ignorable warnings are ignored. if false (or missing), any warnings cause request to fail (default to false).</param>
    /// <param name="type">type (required).</param>
    public ServiceDescriptionUpdate(string url = default, string restServiceCode = default,
        string newRestServiceCode = default, bool ignoreWarnings = false, ServiceType type = default)
    {
        // to ensure "url" is required (not null)
        Url = url ?? throw new ArgumentNullException(nameof(url),
            "url is a required property for ServiceDescriptionUpdate and cannot be null");
        Type = type;
        RestServiceCode = restServiceCode;
        NewRestServiceCode = newRestServiceCode;
        IgnoreWarnings = ignoreWarnings;
    }

    /// <summary>
    /// path for the service description file
    /// </summary>
    /// <value>path for the service description file</value>
    [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = false)]
    public string Url { get; }

    /// <summary>
    /// service code for REST service
    /// </summary>
    /// <value>service code for REST service</value>
    [DataMember(Name = "rest_service_code", EmitDefaultValue = false)]
    public string RestServiceCode { get; }

    /// <summary>
    /// new service code for REST service
    /// </summary>
    /// <value>new service code for REST service</value>
    [DataMember(Name = "new_rest_service_code", EmitDefaultValue = false)]
    public string NewRestServiceCode { get; }

    /// <summary>
    /// if true, any ignorable warnings are ignored. if false (or missing), any warnings cause request to fail
    /// </summary>
    /// <value>if true, any ignorable warnings are ignored. if false (or missing), any warnings cause request to fail</value>
    [DataMember(Name = "ignore_warnings", EmitDefaultValue = true)]
    public bool IgnoreWarnings { get; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class ServiceDescriptionUpdate {\n");
        sb.Append("  Url: ").Append(Url).Append('\n');
        sb.Append("  RestServiceCode: ").Append(RestServiceCode).Append('\n');
        sb.Append("  NewRestServiceCode: ").Append(NewRestServiceCode).Append('\n');
        sb.Append("  IgnoreWarnings: ").Append(IgnoreWarnings).Append('\n');
        sb.Append("  Type: ").Append(Type).Append('\n');
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return Equals(input as ServiceDescriptionUpdate);
    }

    /// <summary>
    /// Returns true if ServiceDescriptionUpdate instances are equal
    /// </summary>
    /// <param name="input">Instance of ServiceDescriptionUpdate to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(ServiceDescriptionUpdate input)
    {
        if (input == null) return false;
        return
            (
                Url == input.Url ||
                (Url != null &&
                 Url.Equals(input.Url))
            ) &&
            (
                RestServiceCode == input.RestServiceCode ||
                (RestServiceCode != null &&
                 RestServiceCode.Equals(input.RestServiceCode))
            ) &&
            (
                NewRestServiceCode == input.NewRestServiceCode ||
                (NewRestServiceCode != null &&
                 NewRestServiceCode.Equals(input.NewRestServiceCode))
            ) &&
            (
                IgnoreWarnings == input.IgnoreWarnings ||
                IgnoreWarnings.Equals(input.IgnoreWarnings)
            ) &&
            (
                Type == input.Type ||
                Type.Equals(input.Type)
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            if (Url != null) hashCode = hashCode * 59 + Url.GetHashCode();
            if (RestServiceCode != null) hashCode = hashCode * 59 + RestServiceCode.GetHashCode();
            if (NewRestServiceCode != null) hashCode = hashCode * 59 + NewRestServiceCode.GetHashCode();
            hashCode = hashCode * 59 + IgnoreWarnings.GetHashCode();
            hashCode = hashCode * 59 + Type.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        // Url (string) maxLength
        if (Url is {Length: > 255})
            yield return new ValidationResult("Invalid value for Url, length must be less than 255.", new[] {"Url"});

        // Url (string) minLength
        if (Url is {Length: < 1})
            yield return new ValidationResult("Invalid value for Url, length must be greater than 1.", new[] {"Url"});

        // RestServiceCode (string) maxLength
        if (RestServiceCode is {Length: > 255})
            yield return new ValidationResult("Invalid value for RestServiceCode, length must be less than 255.",
                new[] {"RestServiceCode"});

        // RestServiceCode (string) minLength
        if (RestServiceCode is {Length: < 1})
            yield return new ValidationResult("Invalid value for RestServiceCode, length must be greater than 1.",
                new[] {"RestServiceCode"});

        // NewRestServiceCode (string) maxLength
        if (NewRestServiceCode is {Length: > 255})
            yield return new ValidationResult("Invalid value for NewRestServiceCode, length must be less than 255.",
                new[] {"NewRestServiceCode"});

        // NewRestServiceCode (string) minLength
        if (NewRestServiceCode is {Length: < 1})
            yield return new ValidationResult("Invalid value for NewRestServiceCode, length must be greater than 1.",
                new[] {"NewRestServiceCode"});
    }
}