/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace XRoad.Sdk.Model;

/// <summary>
/// object containing and array of ServiceClients
/// </summary>
[DataContract(Name = "ServiceClients")]
public class ServiceClients : IEquatable<ServiceClients>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ServiceClients" /> class.
    /// </summary>
    /// <param name="items">array of ServiceClients.</param>
    public ServiceClients(List<ServiceClient> items = default)
    {
        Items = items;
    }

    /// <summary>
    /// array of ServiceClients
    /// </summary>
    /// <value>array of ServiceClients</value>
    [DataMember(Name = "items", EmitDefaultValue = false)]
    public List<ServiceClient> Items { get; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class ServiceClients {\n");
        sb.Append("  Items: ").Append(Items).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return Equals(input as ServiceClients);
    }

    /// <summary>
    /// Returns true if ServiceClients instances are equal
    /// </summary>
    /// <param name="input">Instance of ServiceClients to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(ServiceClients input)
    {
        if (input == null) return false;
        return
            Items == input.Items ||
            (Items != null &&
             input.Items != null &&
             Items.SequenceEqual(input.Items));
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            if (Items != null) hashCode = hashCode * 59 + Items.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        yield break;
    }
}