/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace XRoad.Sdk.Test.Model;

/// <summary>
///  Class for testing CsrGenerate
/// </summary>
/// <remarks>
/// Please update the test case below to test the model.
/// </remarks>
public class CsrGenerateTests : IDisposable
{
    // TODO uncomment below to declare an instance variable for CsrGenerate
    //private CsrGenerate instance;

    public void Dispose()
    {
        // Cleanup when everything is done.
    }

    /// <summary>
    /// Test an instance of CsrGenerate
    /// </summary>
    [Fact]
    public void CsrGenerateInstanceTest()
    {
        // TODO uncomment below to test "IsType" CsrGenerate
        //Assert.IsType<CsrGenerate>(instance);
    }


    /// <summary>
    /// Test the property 'KeyUsageType'
    /// </summary>
    [Fact]
    public void KeyUsageTypeTest()
    {
        // TODO unit test for the property 'KeyUsageType'
    }

    /// <summary>
    /// Test the property 'CaName'
    /// </summary>
    [Fact]
    public void CaNameTest()
    {
        // TODO unit test for the property 'CaName'
    }

    /// <summary>
    /// Test the property 'CsrFormat'
    /// </summary>
    [Fact]
    public void CsrFormatTest()
    {
        // TODO unit test for the property 'CsrFormat'
    }

    /// <summary>
    /// Test the property 'MemberId'
    /// </summary>
    [Fact]
    public void MemberIdTest()
    {
        // TODO unit test for the property 'MemberId'
    }

    /// <summary>
    /// Test the property 'SubjectFieldValues'
    /// </summary>
    [Fact]
    public void SubjectFieldValuesTest()
    {
        // TODO unit test for the property 'SubjectFieldValues'
    }
}