/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace XRoad.Sdk.Test.Model;

/// <summary>
///  Class for testing DistinguishedName
/// </summary>
/// <remarks>
/// Please update the test case below to test the model.
/// </remarks>
public class DistinguishedNameTests : IDisposable
{
    // TODO uncomment below to declare an instance variable for DistinguishedName
    //private DistinguishedName instance;

    public void Dispose()
    {
        // Cleanup when everything is done.
    }

    /// <summary>
    /// Test an instance of DistinguishedName
    /// </summary>
    [Fact]
    public void DistinguishedNameInstanceTest()
    {
        // TODO uncomment below to test "IsType" DistinguishedName
        //Assert.IsType<DistinguishedName>(instance);
    }


    /// <summary>
    /// Test the property 'Name'
    /// </summary>
    [Fact]
    public void NameTest()
    {
        // TODO unit test for the property 'Name'
    }
}