/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace XRoad.Sdk.Test.Model;

/// <summary>
///  Class for testing Endpoint
/// </summary>
/// <remarks>
/// Please update the test case below to test the model.
/// </remarks>
public class EndpointTests : IDisposable
{
    // TODO uncomment below to declare an instance variable for Endpoint
    //private Endpoint instance;

    public void Dispose()
    {
        // Cleanup when everything is done.
    }

    /// <summary>
    /// Test an instance of Endpoint
    /// </summary>
    [Fact]
    public void EndpointInstanceTest()
    {
        // TODO uncomment below to test "IsType" Endpoint
        //Assert.IsType<Endpoint>(instance);
    }


    /// <summary>
    /// Test the property 'Id'
    /// </summary>
    [Fact]
    public void IdTest()
    {
        // TODO unit test for the property 'Id'
    }

    /// <summary>
    /// Test the property 'ServiceCode'
    /// </summary>
    [Fact]
    public void ServiceCodeTest()
    {
        // TODO unit test for the property 'ServiceCode'
    }

    /// <summary>
    /// Test the property 'Method'
    /// </summary>
    [Fact]
    public void MethodTest()
    {
        // TODO unit test for the property 'Method'
    }

    /// <summary>
    /// Test the property 'Path'
    /// </summary>
    [Fact]
    public void PathTest()
    {
        // TODO unit test for the property 'Path'
    }

    /// <summary>
    /// Test the property 'Generated'
    /// </summary>
    [Fact]
    public void GeneratedTest()
    {
        // TODO unit test for the property 'Generated'
    }
}