/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace XRoad.Sdk.Test.Model;

/// <summary>
///  Class for testing GroupMember
/// </summary>
/// <remarks>
/// Please update the test case below to test the model.
/// </remarks>
public class GroupMemberTests : IDisposable
{
    // TODO uncomment below to declare an instance variable for GroupMember
    //private GroupMember instance;

    public void Dispose()
    {
        // Cleanup when everything is done.
    }

    /// <summary>
    /// Test an instance of GroupMember
    /// </summary>
    [Fact]
    public void GroupMemberInstanceTest()
    {
        // TODO uncomment below to test "IsType" GroupMember
        //Assert.IsType<GroupMember>(instance);
    }


    /// <summary>
    /// Test the property 'Id'
    /// </summary>
    [Fact]
    public void IdTest()
    {
        // TODO unit test for the property 'Id'
    }

    /// <summary>
    /// Test the property 'Name'
    /// </summary>
    [Fact]
    public void NameTest()
    {
        // TODO unit test for the property 'Name'
    }

    /// <summary>
    /// Test the property 'CreatedAt'
    /// </summary>
    [Fact]
    public void CreatedAtTest()
    {
        // TODO unit test for the property 'CreatedAt'
    }
}