/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace XRoad.Sdk.Test.Model;

/// <summary>
///  Class for testing LocalGroupDescription
/// </summary>
/// <remarks>
/// Please update the test case below to test the model.
/// </remarks>
public class LocalGroupDescriptionTests : IDisposable
{
    // TODO uncomment below to declare an instance variable for LocalGroupDescription
    //private LocalGroupDescription instance;

    public void Dispose()
    {
        // Cleanup when everything is done.
    }

    /// <summary>
    /// Test an instance of LocalGroupDescription
    /// </summary>
    [Fact]
    public void LocalGroupDescriptionInstanceTest()
    {
        // TODO uncomment below to test "IsType" LocalGroupDescription
        //Assert.IsType<LocalGroupDescription>(instance);
    }


    /// <summary>
    /// Test the property 'Description'
    /// </summary>
    [Fact]
    public void DescriptionTest()
    {
        // TODO unit test for the property 'Description'
    }
}