/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace XRoad.Sdk.Test.Model;

/// <summary>
///  Class for testing MemberName
/// </summary>
/// <remarks>
/// Please update the test case below to test the model.
/// </remarks>
public class MemberNameTests : IDisposable
{
    // TODO uncomment below to declare an instance variable for MemberName
    //private MemberName instance;

    public void Dispose()
    {
        // Cleanup when everything is done.
    }

    /// <summary>
    /// Test an instance of MemberName
    /// </summary>
    [Fact]
    public void MemberNameInstanceTest()
    {
        // TODO uncomment below to test "IsType" MemberName
        //Assert.IsType<MemberName>(instance);
    }


    /// <summary>
    /// Test the property '_MemberName'
    /// </summary>
    [Fact]
    public void _MemberNameTest()
    {
        // TODO unit test for the property '_MemberName'
    }
}