/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace XRoad.Sdk.Test.Model;

/// <summary>
///  Class for testing NodeType
/// </summary>
/// <remarks>
/// Please update the test case below to test the model.
/// </remarks>
public class NodeTypeTests : IDisposable
{
    // TODO uncomment below to declare an instance variable for NodeType
    //private NodeType instance;

    public void Dispose()
    {
        // Cleanup when everything is done.
    }

    /// <summary>
    /// Test an instance of NodeType
    /// </summary>
    [Fact]
    public void NodeTypeInstanceTest()
    {
        // TODO uncomment below to test "IsType" NodeType
        //Assert.IsType<NodeType>(instance);
    }
}