/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace XRoad.Sdk.Test.Model;

/// <summary>
///  Class for testing ServiceDescription
/// </summary>
/// <remarks>
/// Please update the test case below to test the model.
/// </remarks>
public class ServiceDescriptionTests : IDisposable
{
    // TODO uncomment below to declare an instance variable for ServiceDescription
    //private ServiceDescription instance;

    public void Dispose()
    {
        // Cleanup when everything is done.
    }

    /// <summary>
    /// Test an instance of ServiceDescription
    /// </summary>
    [Fact]
    public void ServiceDescriptionInstanceTest()
    {
        // TODO uncomment below to test "IsType" ServiceDescription
        //Assert.IsType<ServiceDescription>(instance);
    }


    /// <summary>
    /// Test the property 'Id'
    /// </summary>
    [Fact]
    public void IdTest()
    {
        // TODO unit test for the property 'Id'
    }

    /// <summary>
    /// Test the property 'Url'
    /// </summary>
    [Fact]
    public void UrlTest()
    {
        // TODO unit test for the property 'Url'
    }

    /// <summary>
    /// Test the property 'Type'
    /// </summary>
    [Fact]
    public void TypeTest()
    {
        // TODO unit test for the property 'Type'
    }

    /// <summary>
    /// Test the property 'Disabled'
    /// </summary>
    [Fact]
    public void DisabledTest()
    {
        // TODO unit test for the property 'Disabled'
    }

    /// <summary>
    /// Test the property 'DisabledNotice'
    /// </summary>
    [Fact]
    public void DisabledNoticeTest()
    {
        // TODO unit test for the property 'DisabledNotice'
    }

    /// <summary>
    /// Test the property 'RefreshedAt'
    /// </summary>
    [Fact]
    public void RefreshedAtTest()
    {
        // TODO unit test for the property 'RefreshedAt'
    }

    /// <summary>
    /// Test the property 'Services'
    /// </summary>
    [Fact]
    public void ServicesTest()
    {
        // TODO unit test for the property 'Services'
    }

    /// <summary>
    /// Test the property 'ClientId'
    /// </summary>
    [Fact]
    public void ClientIdTest()
    {
        // TODO unit test for the property 'ClientId'
    }
}