/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace XRoad.Sdk.Test.Model;

/// <summary>
///  Class for testing User
/// </summary>
/// <remarks>
/// Please update the test case below to test the model.
/// </remarks>
public class UserTests : IDisposable
{
    // TODO uncomment below to declare an instance variable for User
    //private User instance;

    public void Dispose()
    {
        // Cleanup when everything is done.
    }

    /// <summary>
    /// Test an instance of User
    /// </summary>
    [Fact]
    public void UserInstanceTest()
    {
        // TODO uncomment below to test "IsType" User
        //Assert.IsType<User>(instance);
    }


    /// <summary>
    /// Test the property 'Username'
    /// </summary>
    [Fact]
    public void UsernameTest()
    {
        // TODO unit test for the property 'Username'
    }

    /// <summary>
    /// Test the property 'Roles'
    /// </summary>
    [Fact]
    public void RolesTest()
    {
        // TODO unit test for the property 'Roles'
    }

    /// <summary>
    /// Test the property 'Permissions'
    /// </summary>
    [Fact]
    public void PermissionsTest()
    {
        // TODO unit test for the property 'Permissions'
    }
}