/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChihabHajji.XRoad.Sdk.Api;
using ChihabHajji.XRoad.Sdk.Model;
using ChihabHajji.XRoad.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChihabHajji.XRoad.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing AccessRights
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccessRightsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccessRights
        //private AccessRights instance;

        public AccessRightsTests()
        {
            // TODO uncomment below to create an instance of AccessRights
            //instance = new AccessRights();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccessRights
        /// </summary>
        [Fact]
        public void AccessRightsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccessRights
            //Assert.IsType<AccessRights>(instance);
        }


        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

    }

}
