/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChihabHajji.XRoad.Sdk.Api;
using ChihabHajji.XRoad.Sdk.Model;
using ChihabHajji.XRoad.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChihabHajji.XRoad.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing GlobalConfDiagnostics
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GlobalConfDiagnosticsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GlobalConfDiagnostics
        //private GlobalConfDiagnostics instance;

        public GlobalConfDiagnosticsTests()
        {
            // TODO uncomment below to create an instance of GlobalConfDiagnostics
            //instance = new GlobalConfDiagnostics();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GlobalConfDiagnostics
        /// </summary>
        [Fact]
        public void GlobalConfDiagnosticsInstanceTest()
        {
            // TODO uncomment below to test "IsType" GlobalConfDiagnostics
            //Assert.IsType<GlobalConfDiagnostics>(instance);
        }


        /// <summary>
        /// Test the property 'StatusClass'
        /// </summary>
        [Fact]
        public void StatusClassTest()
        {
            // TODO unit test for the property 'StatusClass'
        }
        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'PrevUpdateAt'
        /// </summary>
        [Fact]
        public void PrevUpdateAtTest()
        {
            // TODO unit test for the property 'PrevUpdateAt'
        }
        /// <summary>
        /// Test the property 'NextUpdateAt'
        /// </summary>
        [Fact]
        public void NextUpdateAtTest()
        {
            // TODO unit test for the property 'NextUpdateAt'
        }

    }

}
