/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChihabHajji.XRoad.Sdk.Api;
using ChihabHajji.XRoad.Sdk.Model;
using ChihabHajji.XRoad.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChihabHajji.XRoad.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing IgnoreWarnings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IgnoreWarningsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IgnoreWarnings
        //private IgnoreWarnings instance;

        public IgnoreWarningsTests()
        {
            // TODO uncomment below to create an instance of IgnoreWarnings
            //instance = new IgnoreWarnings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IgnoreWarnings
        /// </summary>
        [Fact]
        public void IgnoreWarningsInstanceTest()
        {
            // TODO uncomment below to test "IsType" IgnoreWarnings
            //Assert.IsType<IgnoreWarnings>(instance);
        }


        /// <summary>
        /// Test the property '_IgnoreWarnings'
        /// </summary>
        [Fact]
        public void _IgnoreWarningsTest()
        {
            // TODO unit test for the property '_IgnoreWarnings'
        }

    }

}
