/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChihabHajji.XRoad.Sdk.Api;
using ChihabHajji.XRoad.Sdk.Model;
using ChihabHajji.XRoad.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChihabHajji.XRoad.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing InitialServerConf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InitialServerConfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InitialServerConf
        //private InitialServerConf instance;

        public InitialServerConfTests()
        {
            // TODO uncomment below to create an instance of InitialServerConf
            //instance = new InitialServerConf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InitialServerConf
        /// </summary>
        [Fact]
        public void InitialServerConfInstanceTest()
        {
            // TODO uncomment below to test "IsType" InitialServerConf
            //Assert.IsType<InitialServerConf>(instance);
        }


        /// <summary>
        /// Test the property 'OwnerMemberClass'
        /// </summary>
        [Fact]
        public void OwnerMemberClassTest()
        {
            // TODO unit test for the property 'OwnerMemberClass'
        }
        /// <summary>
        /// Test the property 'OwnerMemberCode'
        /// </summary>
        [Fact]
        public void OwnerMemberCodeTest()
        {
            // TODO unit test for the property 'OwnerMemberCode'
        }
        /// <summary>
        /// Test the property 'SecurityServerCode'
        /// </summary>
        [Fact]
        public void SecurityServerCodeTest()
        {
            // TODO unit test for the property 'SecurityServerCode'
        }
        /// <summary>
        /// Test the property 'SoftwareTokenPin'
        /// </summary>
        [Fact]
        public void SoftwareTokenPinTest()
        {
            // TODO unit test for the property 'SoftwareTokenPin'
        }
        /// <summary>
        /// Test the property 'IgnoreWarnings'
        /// </summary>
        [Fact]
        public void IgnoreWarningsTest()
        {
            // TODO unit test for the property 'IgnoreWarnings'
        }

    }

}
