/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChihabHajji.XRoad.Sdk.Api;
using ChihabHajji.XRoad.Sdk.Model;
using ChihabHajji.XRoad.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChihabHajji.XRoad.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing KeyLabelWithCsrGenerate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KeyLabelWithCsrGenerateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KeyLabelWithCsrGenerate
        //private KeyLabelWithCsrGenerate instance;

        public KeyLabelWithCsrGenerateTests()
        {
            // TODO uncomment below to create an instance of KeyLabelWithCsrGenerate
            //instance = new KeyLabelWithCsrGenerate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KeyLabelWithCsrGenerate
        /// </summary>
        [Fact]
        public void KeyLabelWithCsrGenerateInstanceTest()
        {
            // TODO uncomment below to test "IsType" KeyLabelWithCsrGenerate
            //Assert.IsType<KeyLabelWithCsrGenerate>(instance);
        }


        /// <summary>
        /// Test the property 'KeyLabel'
        /// </summary>
        [Fact]
        public void KeyLabelTest()
        {
            // TODO unit test for the property 'KeyLabel'
        }
        /// <summary>
        /// Test the property 'CsrGenerateRequest'
        /// </summary>
        [Fact]
        public void CsrGenerateRequestTest()
        {
            // TODO unit test for the property 'CsrGenerateRequest'
        }

    }

}
