/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChihabHajji.XRoad.Sdk.Api;
using ChihabHajji.XRoad.Sdk.Model;
using ChihabHajji.XRoad.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChihabHajji.XRoad.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Key
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KeyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Key
        //private Key instance;

        public KeyTests()
        {
            // TODO uncomment below to create an instance of Key
            //instance = new Key();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Key
        /// </summary>
        [Fact]
        public void KeyInstanceTest()
        {
            // TODO uncomment below to test "IsType" Key
            //Assert.IsType<Key>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Certificates'
        /// </summary>
        [Fact]
        public void CertificatesTest()
        {
            // TODO unit test for the property 'Certificates'
        }
        /// <summary>
        /// Test the property 'CertificateSigningRequests'
        /// </summary>
        [Fact]
        public void CertificateSigningRequestsTest()
        {
            // TODO unit test for the property 'CertificateSigningRequests'
        }
        /// <summary>
        /// Test the property 'Usage'
        /// </summary>
        [Fact]
        public void UsageTest()
        {
            // TODO unit test for the property 'Usage'
        }
        /// <summary>
        /// Test the property 'Available'
        /// </summary>
        [Fact]
        public void AvailableTest()
        {
            // TODO unit test for the property 'Available'
        }
        /// <summary>
        /// Test the property 'SavedToConfiguration'
        /// </summary>
        [Fact]
        public void SavedToConfigurationTest()
        {
            // TODO unit test for the property 'SavedToConfiguration'
        }
        /// <summary>
        /// Test the property 'PossibleActions'
        /// </summary>
        [Fact]
        public void PossibleActionsTest()
        {
            // TODO unit test for the property 'PossibleActions'
        }

    }

}
