/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChihabHajji.XRoad.Sdk.Api;
using ChihabHajji.XRoad.Sdk.Model;
using ChihabHajji.XRoad.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChihabHajji.XRoad.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Language
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LanguageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Language
        //private Language instance;

        public LanguageTests()
        {
            // TODO uncomment below to create an instance of Language
            //instance = new Language();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Language
        /// </summary>
        [Fact]
        public void LanguageInstanceTest()
        {
            // TODO uncomment below to test "IsType" Language
            //Assert.IsType<Language>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
