/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChihabHajji.XRoad.Sdk.Api;
using ChihabHajji.XRoad.Sdk.Model;
using ChihabHajji.XRoad.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChihabHajji.XRoad.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ModelClient
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelClientTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModelClient
        //private ModelClient instance;

        public ModelClientTests()
        {
            // TODO uncomment below to create an instance of ModelClient
            //instance = new ModelClient();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModelClient
        /// </summary>
        [Fact]
        public void ModelClientInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModelClient
            //Assert.IsType<ModelClient>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'InstanceId'
        /// </summary>
        [Fact]
        public void InstanceIdTest()
        {
            // TODO unit test for the property 'InstanceId'
        }
        /// <summary>
        /// Test the property 'MemberName'
        /// </summary>
        [Fact]
        public void MemberNameTest()
        {
            // TODO unit test for the property 'MemberName'
        }
        /// <summary>
        /// Test the property 'MemberClass'
        /// </summary>
        [Fact]
        public void MemberClassTest()
        {
            // TODO unit test for the property 'MemberClass'
        }
        /// <summary>
        /// Test the property 'MemberCode'
        /// </summary>
        [Fact]
        public void MemberCodeTest()
        {
            // TODO unit test for the property 'MemberCode'
        }
        /// <summary>
        /// Test the property 'SubsystemCode'
        /// </summary>
        [Fact]
        public void SubsystemCodeTest()
        {
            // TODO unit test for the property 'SubsystemCode'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'HasValidLocalSignCert'
        /// </summary>
        [Fact]
        public void HasValidLocalSignCertTest()
        {
            // TODO unit test for the property 'HasValidLocalSignCert'
        }
        /// <summary>
        /// Test the property 'ConnectionType'
        /// </summary>
        [Fact]
        public void ConnectionTypeTest()
        {
            // TODO unit test for the property 'ConnectionType'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
