/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChihabHajji.XRoad.Sdk.Api;
using ChihabHajji.XRoad.Sdk.Model;
using ChihabHajji.XRoad.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChihabHajji.XRoad.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing OcspResponderDiagnostics
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OcspResponderDiagnosticsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OcspResponderDiagnostics
        //private OcspResponderDiagnostics instance;

        public OcspResponderDiagnosticsTests()
        {
            // TODO uncomment below to create an instance of OcspResponderDiagnostics
            //instance = new OcspResponderDiagnostics();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OcspResponderDiagnostics
        /// </summary>
        [Fact]
        public void OcspResponderDiagnosticsInstanceTest()
        {
            // TODO uncomment below to test "IsType" OcspResponderDiagnostics
            //Assert.IsType<OcspResponderDiagnostics>(instance);
        }


        /// <summary>
        /// Test the property 'DistinguishedName'
        /// </summary>
        [Fact]
        public void DistinguishedNameTest()
        {
            // TODO unit test for the property 'DistinguishedName'
        }
        /// <summary>
        /// Test the property 'OcspResponders'
        /// </summary>
        [Fact]
        public void OcspRespondersTest()
        {
            // TODO unit test for the property 'OcspResponders'
        }

    }

}
