/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChihabHajji.XRoad.Sdk.Api;
using ChihabHajji.XRoad.Sdk.Model;
using ChihabHajji.XRoad.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChihabHajji.XRoad.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing TokenCertificate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenCertificateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokenCertificate
        //private TokenCertificate instance;

        public TokenCertificateTests()
        {
            // TODO uncomment below to create an instance of TokenCertificate
            //instance = new TokenCertificate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokenCertificate
        /// </summary>
        [Fact]
        public void TokenCertificateInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokenCertificate
            //Assert.IsType<TokenCertificate>(instance);
        }


        /// <summary>
        /// Test the property 'OcspStatus'
        /// </summary>
        [Fact]
        public void OcspStatusTest()
        {
            // TODO unit test for the property 'OcspStatus'
        }
        /// <summary>
        /// Test the property 'OwnerId'
        /// </summary>
        [Fact]
        public void OwnerIdTest()
        {
            // TODO unit test for the property 'OwnerId'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'SavedToConfiguration'
        /// </summary>
        [Fact]
        public void SavedToConfigurationTest()
        {
            // TODO unit test for the property 'SavedToConfiguration'
        }
        /// <summary>
        /// Test the property 'CertificateDetails'
        /// </summary>
        [Fact]
        public void CertificateDetailsTest()
        {
            // TODO unit test for the property 'CertificateDetails'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'PossibleActions'
        /// </summary>
        [Fact]
        public void PossibleActionsTest()
        {
            // TODO unit test for the property 'PossibleActions'
        }

    }

}
