/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ChihabHajji.XRoad.Sdk.Client.OpenAPIDateConverter;

namespace ChihabHajji.XRoad.Sdk.Model
{
    /// <summary>
    /// service type
    /// </summary>
    /// <value>service type</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ServiceType
    {
        /// <summary>
        /// Enum WSDL for value: WSDL
        /// </summary>
        [EnumMember(Value = "WSDL")]
        WSDL = 1,

        /// <summary>
        /// Enum REST for value: REST
        /// </summary>
        [EnumMember(Value = "REST")]
        REST = 2,

        /// <summary>
        /// Enum OPENAPI3 for value: OPENAPI3
        /// </summary>
        [EnumMember(Value = "OPENAPI3")]
        OPENAPI3 = 3

    }

}
