/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using XRoad.Sdk.Api;
using Xunit;

// uncomment below to import models
//using XRoad.Sdk.Model;

namespace XRoad.Sdk.Test.Api;

/// <summary>
///  Class for testing CertificateAuthoritiesApi
/// </summary>
/// <remarks>
/// Please update the test case below to test the API endpoint.
/// </remarks>
public class CertificateAuthoritiesApiTests : IDisposable
{
    private CertificateAuthoritiesApi _instance = new();

    public void Dispose()
    {
        // Cleanup when everything is done.
    }

    /// <summary>
    /// Test an instance of CertificateAuthoritiesApi
    /// </summary>
    [Fact]
    public void InstanceTest()
    {
        // TODO uncomment below to test 'IsType' CertificateAuthoritiesApi
        //Assert.IsType<CertificateAuthoritiesApi>(instance);
    }

    /// <summary>
    /// Test GetApprovedCertificateAuthorities
    /// </summary>
    [Fact]
    public void GetApprovedCertificateAuthoritiesTest()
    {
        // TODO uncomment below to test the method and replace null with proper value
        //KeyUsageType? keyUsageType = null;
        //bool? includeIntermediateCas = null;
        //var response = instance.GetApprovedCertificateAuthorities(keyUsageType, includeIntermediateCas);
        //Assert.IsType<List<CertificateAuthority>>(response);
    }

    /// <summary>
    /// Test GetSubjectFieldDescriptions
    /// </summary>
    [Fact]
    public void GetSubjectFieldDescriptionsTest()
    {
        // TODO uncomment below to test the method and replace null with proper value
        //string caName = null;
        //KeyUsageType keyUsageType = null;
        //string keyId = null;
        //string memberId = null;
        //bool? isNewMember = null;
        //var response = instance.GetSubjectFieldDescriptions(caName, keyUsageType, keyId, memberId, isNewMember);
        //Assert.IsType<List<CsrSubjectFieldDescription>>(response);
    }
}