/*
 * X-Road Security Server Admin API
 *
 * X-Road Security Server Admin API. Note that the error metadata responses described in some endpoints are subjects to change and may be updated in upcoming versions.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@niis.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using XRoad.Sdk.Api;
using Xunit;

// uncomment below to import models
//using XRoad.Sdk.Model;

namespace XRoad.Sdk.Test.Api;

/// <summary>
///  Class for testing SecurityServersApi
/// </summary>
/// <remarks>
/// Please update the test case below to test the API endpoint.
/// </remarks>
public class SecurityServersApiTests : IDisposable
{
    private SecurityServersApi instance;

    public SecurityServersApiTests()
    {
        instance = new SecurityServersApi();
    }

    public void Dispose()
    {
        // Cleanup when everything is done.
    }

    /// <summary>
    /// Test an instance of SecurityServersApi
    /// </summary>
    [Fact]
    public void InstanceTest()
    {
        // TODO uncomment below to test 'IsType' SecurityServersApi
        //Assert.IsType<SecurityServersApi>(instance);
    }

    /// <summary>
    /// Test GetSecurityServer
    /// </summary>
    [Fact]
    public void GetSecurityServerTest()
    {
        // TODO uncomment below to test the method and replace null with proper value
        //string id = null;
        //var response = instance.GetSecurityServer(id);
        //Assert.IsType<SecurityServer>(response);
    }

    /// <summary>
    /// Test GetSecurityServers
    /// </summary>
    [Fact]
    public void GetSecurityServersTest()
    {
        // TODO uncomment below to test the method and replace null with proper value
        //bool? currentServer = null;
        //var response = instance.GetSecurityServers(currentServer);
        //Assert.IsType<List<SecurityServer>>(response);
    }
}